export const initialRates = [
  {
    from: 'btc',
    to: 'ltc',
    id: 'btcltc',
  },
  {
    from: 'btc',
    to: 'usdt',
    id: 'btcusdt',
  },
  {
    from: 'btc',
    to: 'xmr',
    id: 'btcxmr',
  },
  {
    from: 'btc',
    to: 'eth',
    id: 'btceth',
  },
  {
    from: 'btc',
    to: 'sol',
    id: 'btcsol',
  },
  {
    from: 'btc',
    to: 'trx',
    id: 'btctrx',
  },
  {
    from: 'btc',
    to: 'usd',
    id: 'btcusd',
  },
  {
    from: 'btc',
    to: 'eur',
    id: 'btceur',
  },
  {
    from: 'btc',
    to: 'rub',
    id: 'btcrub',
  },
  {
    from: 'btc',
    to: 'kzt',
    id: 'btckzt',
  },
  {
    from: 'btc',
    to: 'uah',
    id: 'btcuah',
  },
  {
    from: 'btc',
    to: 'ngn',
    id: 'btcngn',
  },
  {
    from: 'btc',
    to: 'cny',
    id: 'btccny',
  },
  {
    from: 'btc',
    to: 'brl',
    id: 'btcbrl',
  },
  {
    from: 'ltc',
    to: 'btc',
    id: 'ltcbtc',
  },
  {
    from: 'ltc',
    to: 'usdt',
    id: 'ltcusdt',
  },
  {
    from: 'ltc',
    to: 'xmr',
    id: 'ltcxmr',
  },
  {
    from: 'ltc',
    to: 'eth',
    id: 'ltceth',
  },
  {
    from: 'ltc',
    to: 'sol',
    id: 'ltcsol',
  },
  {
    from: 'ltc',
    to: 'trx',
    id: 'ltctrx',
  },
  {
    from: 'ltc',
    to: 'usd',
    id: 'ltcusd',
  },
  {
    from: 'ltc',
    to: 'eur',
    id: 'ltceur',
  },
  {
    from: 'ltc',
    to: 'rub',
    id: 'ltcrub',
  },
  {
    from: 'ltc',
    to: 'kzt',
    id: 'ltckzt',
  },
  {
    from: 'ltc',
    to: 'uah',
    id: 'ltcuah',
  },
  {
    from: 'ltc',
    to: 'ngn',
    id: 'ltcngn',
  },
  {
    from: 'ltc',
    to: 'cny',
    id: 'ltccny',
  },
  {
    from: 'ltc',
    to: 'brl',
    id: 'ltcbrl',
  },
  {
    from: 'usdt',
    to: 'btc',
    id: 'usdtbtc',
  },
  {
    from: 'usdt',
    to: 'ltc',
    id: 'usdtltc',
  },
  {
    from: 'usdt',
    to: 'xmr',
    id: 'usdtxmr',
  },
  {
    from: 'usdt',
    to: 'eth',
    id: 'usdteth',
  },
  {
    from: 'usdt',
    to: 'sol',
    id: 'usdtsol',
  },
  {
    from: 'usdt',
    to: 'trx',
    id: 'usdttrx',
  },
  {
    from: 'usdt',
    to: 'usd',
    id: 'usdtusd',
  },
  {
    from: 'usdt',
    to: 'eur',
    id: 'usdteur',
  },
  {
    from: 'usdt',
    to: 'rub',
    id: 'usdtrub',
  },
  {
    from: 'usdt',
    to: 'kzt',
    id: 'usdtkzt',
  },
  {
    from: 'usdt',
    to: 'uah',
    id: 'usdtuah',
  },
  {
    from: 'usdt',
    to: 'ngn',
    id: 'usdtngn',
  },
  {
    from: 'usdt',
    to: 'cny',
    id: 'usdtcny',
  },
  {
    from: 'usdt',
    to: 'brl',
    id: 'usdtbrl',
  },
  {
    from: 'xmr',
    to: 'btc',
    id: 'xmrbtc',
  },
  {
    from: 'xmr',
    to: 'ltc',
    id: 'xmrltc',
  },
  {
    from: 'xmr',
    to: 'usdt',
    id: 'xmrusdt',
  },
  {
    from: 'xmr',
    to: 'eth',
    id: 'xmreth',
  },
  {
    from: 'xmr',
    to: 'sol',
    id: 'xmrsol',
  },
  {
    from: 'xmr',
    to: 'trx',
    id: 'xmrtrx',
  },
  {
    from: 'xmr',
    to: 'usd',
    id: 'xmrusd',
  },
  {
    from: 'xmr',
    to: 'eur',
    id: 'xmreur',
  },
  {
    from: 'xmr',
    to: 'rub',
    id: 'xmrrub',
  },
  {
    from: 'xmr',
    to: 'kzt',
    id: 'xmrkzt',
  },
  {
    from: 'xmr',
    to: 'uah',
    id: 'xmruah',
  },
  {
    from: 'xmr',
    to: 'ngn',
    id: 'xmrngn',
  },
  {
    from: 'xmr',
    to: 'cny',
    id: 'xmrcny',
  },
  {
    from: 'xmr',
    to: 'brl',
    id: 'xmrbrl',
  },
  {
    from: 'eth',
    to: 'btc',
    id: 'ethbtc',
  },
  {
    from: 'eth',
    to: 'ltc',
    id: 'ethltc',
  },
  {
    from: 'eth',
    to: 'usdt',
    id: 'ethusdt',
  },
  {
    from: 'eth',
    to: 'xmr',
    id: 'ethxmr',
  },
  {
    from: 'eth',
    to: 'sol',
    id: 'ethsol',
  },
  {
    from: 'eth',
    to: 'trx',
    id: 'ethtrx',
  },
  {
    from: 'eth',
    to: 'usd',
    id: 'ethusd',
  },
  {
    from: 'eth',
    to: 'eur',
    id: 'etheur',
  },
  {
    from: 'eth',
    to: 'rub',
    id: 'ethrub',
  },
  {
    from: 'eth',
    to: 'kzt',
    id: 'ethkzt',
  },
  {
    from: 'eth',
    to: 'uah',
    id: 'ethuah',
  },
  {
    from: 'eth',
    to: 'ngn',
    id: 'ethngn',
  },
  {
    from: 'eth',
    to: 'cny',
    id: 'ethcny',
  },
  {
    from: 'eth',
    to: 'brl',
    id: 'ethbrl',
  },
  {
    from: 'sol',
    to: 'btc',
    id: 'solbtc',
  },
  {
    from: 'sol',
    to: 'ltc',
    id: 'solltc',
  },
  {
    from: 'sol',
    to: 'usdt',
    id: 'solusdt',
  },
  {
    from: 'sol',
    to: 'xmr',
    id: 'solxmr',
  },
  {
    from: 'sol',
    to: 'eth',
    id: 'soleth',
  },
  {
    from: 'sol',
    to: 'trx',
    id: 'soltrx',
  },
  {
    from: 'sol',
    to: 'usd',
    id: 'solusd',
  },
  {
    from: 'sol',
    to: 'eur',
    id: 'soleur',
  },
  {
    from: 'sol',
    to: 'rub',
    id: 'solrub',
  },
  {
    from: 'sol',
    to: 'kzt',
    id: 'solkzt',
  },
  {
    from: 'sol',
    to: 'uah',
    id: 'soluah',
  },
  {
    from: 'sol',
    to: 'ngn',
    id: 'solngn',
  },
  {
    from: 'sol',
    to: 'cny',
    id: 'solcny',
  },
  {
    from: 'sol',
    to: 'brl',
    id: 'solbrl',
  },
  {
    from: 'trx',
    to: 'btc',
    id: 'trxbtc',
  },
  {
    from: 'trx',
    to: 'ltc',
    id: 'trxltc',
  },
  {
    from: 'trx',
    to: 'usdt',
    id: 'trxusdt',
  },
  {
    from: 'trx',
    to: 'xmr',
    id: 'trxxmr',
  },
  {
    from: 'trx',
    to: 'eth',
    id: 'trxeth',
  },
  {
    from: 'trx',
    to: 'sol',
    id: 'trxsol',
  },
  {
    from: 'trx',
    to: 'usd',
    id: 'trxusd',
  },
  {
    from: 'trx',
    to: 'eur',
    id: 'trxeur',
  },
  {
    from: 'trx',
    to: 'rub',
    id: 'trxrub',
  },
  {
    from: 'trx',
    to: 'kzt',
    id: 'trxkzt',
  },
  {
    from: 'trx',
    to: 'uah',
    id: 'trxuah',
  },
  {
    from: 'trx',
    to: 'ngn',
    id: 'trxngn',
  },
  {
    from: 'trx',
    to: 'cny',
    id: 'trxcny',
  },
  {
    from: 'trx',
    to: 'brl',
    id: 'trxbrl',
  },
  { from: 'usd', to: 'btc', id: 'usdbtc' },
  { from: 'usd', to: 'ltc', id: 'usdltc' },
  { from: 'usd', to: 'usdt', id: 'usdusdt' },
  { from: 'usd', to: 'xmr', id: 'usdxmr' },
  { from: 'usd', to: 'eth', id: 'usdeth' },
  { from: 'usd', to: 'sol', id: 'usdsol' },
  { from: 'usd', to: 'trx', id: 'usdtrx' },
  { from: 'eur', to: 'btc', id: 'eurbtc' },
  { from: 'eur', to: 'ltc', id: 'eurltc' },
  { from: 'eur', to: 'usdt', id: 'eurusdt' },
  { from: 'eur', to: 'xmr', id: 'eurxmr' },
  { from: 'eur', to: 'eth', id: 'eureth' },
  { from: 'eur', to: 'sol', id: 'eursol' },
  { from: 'eur', to: 'trx', id: 'eurtrx' },
  { from: 'rub', to: 'btc', id: 'rubbtc' },
  { from: 'rub', to: 'ltc', id: 'rubltc' },
  { from: 'rub', to: 'usdt', id: 'rubusdt' },
  { from: 'rub', to: 'xmr', id: 'rubxmr' },
  { from: 'rub', to: 'eth', id: 'rubeth' },
  { from: 'rub', to: 'sol', id: 'rubsol' },
  { from: 'rub', to: 'trx', id: 'rubtrx' },
  { from: 'kzt', to: 'btc', id: 'kztbtc' },
  { from: 'kzt', to: 'ltc', id: 'kztltc' },
  { from: 'kzt', to: 'usdt', id: 'kztusdt' },
  { from: 'kzt', to: 'xmr', id: 'kztxmr' },
  { from: 'kzt', to: 'eth', id: 'kzteth' },
  { from: 'kzt', to: 'sol', id: 'kztsol' },
  { from: 'kzt', to: 'trx', id: 'kzttrx' },
  { from: 'uah', to: 'btc', id: 'uahbtc' },
  { from: 'uah', to: 'ltc', id: 'uahltc' },
  { from: 'uah', to: 'usdt', id: 'uahusdt' },
  { from: 'uah', to: 'xmr', id: 'uahxmr' },
  { from: 'uah', to: 'eth', id: 'uaheth' },
  { from: 'uah', to: 'sol', id: 'uahsol' },
  { from: 'uah', to: 'trx', id: 'uahtrx' },
  { from: 'ngn', to: 'btc', id: 'ngnbtc' },
  { from: 'ngn', to: 'ltc', id: 'ngnltc' },
  { from: 'ngn', to: 'usdt', id: 'ngnusdt' },
  { from: 'ngn', to: 'xmr', id: 'ngnxmr' },
  { from: 'ngn', to: 'eth', id: 'ngneth' },
  { from: 'ngn', to: 'sol', id: 'ngnsol' },
  { from: 'ngn', to: 'trx', id: 'ngntrx' },
  { from: 'cny', to: 'btc', id: 'cnybtc' },
  { from: 'cny', to: 'ltc', id: 'cnyltc' },
  { from: 'cny', to: 'usdt', id: 'cnyusdt' },
  { from: 'cny', to: 'xmr', id: 'cnyxmr' },
  { from: 'cny', to: 'eth', id: 'cnyeth' },
  { from: 'cny', to: 'sol', id: 'cnysol' },
  { from: 'cny', to: 'trx', id: 'cnytrx' },
  { from: 'brl', to: 'btc', id: 'brlbtc' },
  { from: 'brl', to: 'ltc', id: 'brlltc' },
  { from: 'brl', to: 'usdt', id: 'brlusdt' },
  { from: 'brl', to: 'xmr', id: 'brlxmr' },
  { from: 'brl', to: 'eth', id: 'brleth' },
  { from: 'brl', to: 'sol', id: 'brlsol' },
  { from: 'brl', to: 'trx', id: 'brltrx' },
];
